// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClWBobE4fdGgCg-3fXYJJjWwHNBKokFo0',
    appId: '1:215420339393:web:158206dd8b2fdd14064040',
    messagingSenderId: '215420339393',
    projectId: 'umar-s-fyp',
    authDomain: 'umar-s-fyp.firebaseapp.com',
    storageBucket: 'umar-s-fyp.firebasestorage.app',
    measurementId: 'G-12L0G5RQSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC08h_FvsDCNcM2TyFUn3taWINH4TzCqTI',
    appId: '1:215420339393:android:326baf89f52b0508064040',
    messagingSenderId: '215420339393',
    projectId: 'umar-s-fyp',
    storageBucket: 'umar-s-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvZyjbZgPkqIyYvj_g6lJd4hiGYRm0bH8',
    appId: '1:215420339393:ios:0c5694e7b7d0041f064040',
    messagingSenderId: '215420339393',
    projectId: 'umar-s-fyp',
    storageBucket: 'umar-s-fyp.firebasestorage.app',
    iosBundleId: 'com.example.novaPrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvZyjbZgPkqIyYvj_g6lJd4hiGYRm0bH8',
    appId: '1:215420339393:ios:0c5694e7b7d0041f064040',
    messagingSenderId: '215420339393',
    projectId: 'umar-s-fyp',
    storageBucket: 'umar-s-fyp.firebasestorage.app',
    iosBundleId: 'com.example.novaPrep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClWBobE4fdGgCg-3fXYJJjWwHNBKokFo0',
    appId: '1:215420339393:web:62956a8f9012b9a1064040',
    messagingSenderId: '215420339393',
    projectId: 'umar-s-fyp',
    authDomain: 'umar-s-fyp.firebaseapp.com',
    storageBucket: 'umar-s-fyp.firebasestorage.app',
    measurementId: 'G-HKENTPRC3L',
  );
}
