// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASE-WSYQGbTo0XqnUg-BEO6s5HFd7BkYU',
    appId: '1:140641716848:web:401ffb32633505ae3c42b5',
    messagingSenderId: '140641716848',
    projectId: 'moiz-fyp',
    authDomain: 'moiz-fyp.firebaseapp.com',
    storageBucket: 'moiz-fyp.firebasestorage.app',
    measurementId: 'G-CSSTHKD25P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJfmKZxqSce9NyhPNQxvmnYVfJ0fDjZgY',
    appId: '1:140641716848:android:48ab7582b53118b63c42b5',
    messagingSenderId: '140641716848',
    projectId: 'moiz-fyp',
    storageBucket: 'moiz-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvckex2O1Aeh73hdBjohlagnjvtUFDGlw',
    appId: '1:140641716848:ios:74f139080ac361733c42b5',
    messagingSenderId: '140641716848',
    projectId: 'moiz-fyp',
    storageBucket: 'moiz-fyp.firebasestorage.app',
    iosBundleId: 'com.example.novaPrep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvckex2O1Aeh73hdBjohlagnjvtUFDGlw',
    appId: '1:140641716848:ios:74f139080ac361733c42b5',
    messagingSenderId: '140641716848',
    projectId: 'moiz-fyp',
    storageBucket: 'moiz-fyp.firebasestorage.app',
    iosBundleId: 'com.example.novaPrep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASE-WSYQGbTo0XqnUg-BEO6s5HFd7BkYU',
    appId: '1:140641716848:web:8924dd458e1387df3c42b5',
    messagingSenderId: '140641716848',
    projectId: 'moiz-fyp',
    authDomain: 'moiz-fyp.firebaseapp.com',
    storageBucket: 'moiz-fyp.firebasestorage.app',
    measurementId: 'G-DCC77SJYXQ',
  );

}